spring:
  application:
    name: spring-transaction-demo
  datasource:
    druid:
      url: jdbc:mysql://mysql-server:3306/test?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
      initial-size: 5
      max-active: 5


# mybatis配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
